/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.ifpr.thelaststanding;

import br.edu.ifpr.thelaststanding.conexao.Conexao;
import br.edu.ifpr.thelaststanding.personagens.Guerreiro;
import br.edu.ifpr.thelaststanding.personagens.Mago;

import java.sql.PreparedStatement;
import java.util.Objects;
import javax.swing.JOptionPane;

/**
 * @author Aluno
 */
public class CadastroPersonagem extends javax.swing.JFrame {

    /**
     * Creates new form CadastroGuerreiro
     */
    public CadastroPersonagem() {
        initComponents();
        // Gerar um inteiro entre min e max
        int ataque = (int) (Math.random() * (20 - 15 + 1) + 15);
        txtPontosAtaque.setText("" + ataque);

        int defesa = (int) (Math.random() * (20 - 10 + 1) + 15);
        txtPontosDefesa.setText("" + defesa);

        int ataque1 = (int) (Math.random() * (30 - 20 + 1) + 15);
        txtPontosAtaque1.setText("" + ataque1);

        int defesa1 = (int) (Math.random() * (10 - 5 + 1) + 10);
        txtPontosDefesa1.setText("" + defesa1);
        
        jButton3.setVisible(false);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPontosVida = new javax.swing.JTextField();
        txtPontosAtaque = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPontosDefesa = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtPontosDefesa1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtPontosAtaque1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtPontosVida1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtNome1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(1280, 960));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 960));
        getContentPane().setLayout(null);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Guerreiro.png"))); // NOI18N
        jLabel1.setText("Foto do Gueirreiro");
        jLabel1.setAlignmentY(0.0F);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(350, 310, 310, 300);

        jLabel2.setText("Nome");
        jLabel2.setAlignmentY(0.0F);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 300, 50, 16);

        txtNome.setAlignmentX(0.0F);
        txtNome.setAlignmentY(0.0F);
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtNome);
        txtNome.setBounds(150, 330, 211, 30);

        jLabel3.setText("Pontos de Vida");
        jLabel3.setAlignmentY(0.0F);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 360, 100, 16);

        txtPontosVida.setEditable(false);
        txtPontosVida.setText("100");
        txtPontosVida.setAlignmentX(0.0F);
        txtPontosVida.setAlignmentY(0.0F);
        txtPontosVida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPontosVidaActionPerformed(evt);
            }
        });
        getContentPane().add(txtPontosVida);
        txtPontosVida.setBounds(150, 380, 211, 22);

        txtPontosAtaque.setEditable(false);
        txtPontosAtaque.setAlignmentX(0.0F);
        txtPontosAtaque.setAlignmentY(0.0F);
        txtPontosAtaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPontosAtaqueActionPerformed(evt);
            }
        });
        getContentPane().add(txtPontosAtaque);
        txtPontosAtaque.setBounds(150, 430, 211, 22);

        jLabel4.setText("Pontos de Ataque");
        jLabel4.setAlignmentY(0.0F);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(150, 410, 100, 16);

        jLabel5.setText("Item");
        jLabel5.setAlignmentY(0.0F);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(150, 510, 70, 16);

        txtPontosDefesa.setEditable(false);
        txtPontosDefesa.setAlignmentX(0.0F);
        txtPontosDefesa.setAlignmentY(0.0F);
        txtPontosDefesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPontosDefesaActionPerformed(evt);
            }
        });
        getContentPane().add(txtPontosDefesa);
        txtPontosDefesa.setBounds(150, 480, 211, 22);

        jButton1.setText("Salvar Guerreiro");
        jButton1.setAlignmentY(0.0F);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(280, 620, 130, 23);

        jButton2.setText("Salvar Mistico");
        jButton2.setAlignmentY(0.0F);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(900, 620, 130, 23);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/MagoNormal.png"))); // NOI18N
        jLabel8.setText("Foto do Mistico");
        jLabel8.setAlignmentY(0.0F);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(670, 300, 249, 300);

        txtPontosDefesa1.setEditable(false);
        txtPontosDefesa1.setAlignmentX(0.0F);
        txtPontosDefesa1.setAlignmentY(0.0F);
        txtPontosDefesa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPontosDefesa1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtPontosDefesa1);
        txtPontosDefesa1.setBounds(930, 480, 211, 22);

        jLabel11.setText("Pontos de Defesa");
        jLabel11.setAlignmentY(0.0F);
        getContentPane().add(jLabel11);
        jLabel11.setBounds(930, 460, 100, 16);

        txtPontosAtaque1.setEditable(false);
        txtPontosAtaque1.setAlignmentX(0.0F);
        txtPontosAtaque1.setAlignmentY(0.0F);
        txtPontosAtaque1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPontosAtaque1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtPontosAtaque1);
        txtPontosAtaque1.setBounds(930, 430, 211, 22);

        jLabel12.setText("Pontos de Ataque");
        jLabel12.setAlignmentY(0.0F);
        getContentPane().add(jLabel12);
        jLabel12.setBounds(930, 410, 110, 16);

        txtPontosVida1.setEditable(false);
        txtPontosVida1.setText("100");
        txtPontosVida1.setAlignmentX(0.0F);
        txtPontosVida1.setAlignmentY(0.0F);
        txtPontosVida1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPontosVida1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtPontosVida1);
        txtPontosVida1.setBounds(930, 380, 211, 22);

        jLabel13.setText("Pontos de Vida");
        jLabel13.setAlignmentY(0.0F);
        getContentPane().add(jLabel13);
        jLabel13.setBounds(930, 360, 100, 16);

        txtNome1.setAlignmentX(0.0F);
        txtNome1.setAlignmentY(0.0F);
        txtNome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNome1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtNome1);
        txtNome1.setBounds(930, 330, 211, 30);

        jLabel14.setText("Nome");
        jLabel14.setAlignmentY(0.0F);
        getContentPane().add(jLabel14);
        jLabel14.setBounds(930, 300, 60, 16);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Vazio>", "Cajado De Gelo", "Grimorio das Sombras" }));
        jComboBox1.setAlignmentX(0.0F);
        jComboBox1.setAlignmentY(0.0F);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(930, 530, 220, 22);

        jLabel15.setText("Pontos de Defesa");
        jLabel15.setAlignmentY(0.0F);
        getContentPane().add(jLabel15);
        jLabel15.setBounds(150, 460, 110, 16);

        jLabel6.setText("Item");
        jLabel6.setAlignmentY(0.0F);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(930, 510, 40, 16);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Vazio>", "Espada Flamejante", "Crucifixo" }));
        jComboBox2.setAlignmentX(0.0F);
        jComboBox2.setAlignmentY(0.0F);
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(150, 530, 210, 22);

        jButton3.setBackground(new java.awt.Color(255, 255, 204));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/confirm-button.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(590, 720, 170, 50);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/fundo-menu.jpeg"))); // NOI18N
        jLabel7.setText("jLabel7");
        jLabel7.setMaximumSize(new java.awt.Dimension(1280, 960));
        jLabel7.setMinimumSize(new java.awt.Dimension(1280, 960));
        jLabel7.setPreferredSize(new java.awt.Dimension(1280, 960));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 0, 1280, 960);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtPontosVidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPontosVidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPontosVidaActionPerformed

    private void txtPontosAtaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPontosAtaqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPontosAtaqueActionPerformed

    private void txtPontosDefesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPontosDefesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPontosDefesaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Guerreiro guerreiro = new Guerreiro();

        guerreiro.setNome(txtNome.getText());
        guerreiro.setPontosVida(Integer.parseInt(txtPontosVida.getText()));
        guerreiro.setPontosAtaque(Integer.parseInt(txtPontosAtaque.getText()));
        guerreiro.setPontosDefesa(Integer.parseInt(txtPontosDefesa.getText()));


        salvar(guerreiro);
        
        
        if(jbutton1value == 1 && jbutton2value == 1){
            jButton3.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Mago mago = new Mago();

        mago.setNome(txtNome1.getText());
        mago.setPontosVida(Integer.parseInt(txtPontosVida1.getText()));
        mago.setPontosAtaque(Integer.parseInt(txtPontosAtaque1.getText()));
        mago.setPontosDefesa(Integer.parseInt(txtPontosDefesa1.getText()));


        salvar(mago);
        
        if(jbutton1value == 1 && jbutton2value == 1){
            jButton3.setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtPontosDefesa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPontosDefesa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPontosDefesa1ActionPerformed

    private void txtPontosAtaque1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPontosAtaque1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPontosAtaque1ActionPerformed

    private void txtPontosVida1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPontosVida1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPontosVida1ActionPerformed

    private void txtNome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNome1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNome1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        TelaBatalha tela = new TelaBatalha();
        this.dispose();
        tela.setVisible(true);

        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroPersonagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNome1;
    private javax.swing.JTextField txtPontosAtaque;
    private javax.swing.JTextField txtPontosAtaque1;
    private javax.swing.JTextField txtPontosDefesa;
    private javax.swing.JTextField txtPontosDefesa1;
    private javax.swing.JTextField txtPontosVida;
    private javax.swing.JTextField txtPontosVida1;
    // End of variables declaration//GEN-END:variables
    private int jbutton1value = 0;
    private int jbutton2value = 0;
    
    private void salvar(Guerreiro guerreiro) {
        String sql = "INSERT "
                + "INTO `tb_guerreiro` "
                + "(`nome`, `ponto_vida`, `ponto_ataque`, `ponto_defesa`, `forca`, `velocidade`) "
                + "VALUES "
                + "(?, ?, ?, ?, ?, ?);";
        try {
            PreparedStatement preparacaoDaInstrucao = Conexao.getConexao().prepareStatement(sql);
            preparacaoDaInstrucao.setString(1, guerreiro.getNome());
            preparacaoDaInstrucao.setDouble(2, guerreiro.getPontosVida());
            preparacaoDaInstrucao.setInt(3, guerreiro.getPontosAtaque());
            preparacaoDaInstrucao.setInt(4, guerreiro.getPontosDefesa());
            preparacaoDaInstrucao.setInt(5, guerreiro.getForca());
            preparacaoDaInstrucao.setInt(6, guerreiro.getVelocidade());
            preparacaoDaInstrucao.executeUpdate();
            JOptionPane.showMessageDialog(this, "Salvo com sucesso!");
            // libera a memória da janela
            jButton1.setVisible(false);
            jbutton1value = 1;

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao salvar!");
            jButton1.setVisible(true);
            jbutton1value = 0;
        }

    }

    private void salvar(Mago mago) {
        String sql = "INSERT "
                + "INTO `tb_mago` "
                + "(`nome`, `ponto_vida`, `ponto_ataque`, `ponto_defesa`, `magia`, `poder_sombrio`) "
                + "VALUES "
                + "(?, ?, ?, ?, ?, ?);";
        try {
            PreparedStatement preparacaoDaInstrucao = Conexao.getConexao().prepareStatement(sql);
            preparacaoDaInstrucao.setString(1, mago.getNome());
            preparacaoDaInstrucao.setDouble(2, mago.getPontosVida());
            preparacaoDaInstrucao.setInt(3, mago.getPontosAtaque());
            preparacaoDaInstrucao.setInt(4, mago.getPontosDefesa());
            preparacaoDaInstrucao.setInt(5, mago.getMagia());
            preparacaoDaInstrucao.setInt(6, mago.getPoderSombrio());
            preparacaoDaInstrucao.executeUpdate();
            JOptionPane.showMessageDialog(this, "Salvo com sucesso!");
            // libera a memória da janela
            jButton2.setVisible(false);
            jbutton2value = 1;

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao salvar!");
            jButton2.setVisible(true);
            jbutton2value = 0;
        }
    }
//    private void salvar1(Mistico mistico) {
//        String sql = "INSERT "
//                + "INTO `tb_guerreiro` "
//                + "(`nome`, `ponto_vida`, `ponto_ataque`, `ponto_defesa`, `forca`, `velocidade`) "
//                + "VALUES "
//                + "(?, ?, ?, ?, ?, ?);";
//        try {
//                PreparedStatement preparacaoDaInstrucao = Conexao.getConexao().prepareStatement(sql);
//                preparacaoDaInstrucao.setString(1, guerreiro.getNome());
//                preparacaoDaInstrucao.setInt(2, guerreiro.getPontosVida());
//                preparacaoDaInstrucao.setInt(3, guerreiro.getPontosAtaque());
//                preparacaoDaInstrucao.setInt(4, guerreiro.getPontosDefesa());
//                preparacaoDaInstrucao.setInt(5, guerreiro.getForca());
//                preparacaoDaInstrucao.setInt(6, guerreiro.getVelocidade());
//                preparacaoDaInstrucao.executeUpdate();
//                JOptionPane.showMessageDialog(this, "Salvo com sucesso!");
// // libera a memória da janela
//                
//        } catch (Exception e) {
//                e.printStackTrace();
//                JOptionPane.showMessageDialog(this, "Erro ao salvar!");
//        }
//    }

}
