/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.ifpr.thelaststanding;

import br.edu.ifpr.thelaststanding.conexao.Conexao;
import br.edu.ifpr.thelaststanding.personagens.Guerreiro;
import br.edu.ifpr.thelaststanding.personagens.Mago;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * @author Aluno
 */
public class TelaBatalha extends javax.swing.JFrame {

    /**
     * Creates new form TelaBatalha
     */
    public TelaBatalha() {
        initComponents();

        jLabel1.setVisible(true);
        jLabel2.setVisible(true);
        jLabel3.setVisible(true);
        jLabel4.setVisible(true);
        jLabel5.setVisible(true);
        jLabel6.setVisible(true);
        jLabel7.setVisible(true);
        jLabel8.setVisible(true);
        jLabel9.setVisible(true);
        labelVitoria.setVisible(false);

        jLabel10.setVisible(true);
        jLabel11.setVisible(true);
        jTextField1.setVisible(true);
        jTextField2.setVisible(true);
        jTextField3.setVisible(true);
        jTextField4.setVisible(true);
        jTextField5.setVisible(true);
        jTextField6.setVisible(true);
        returnButton.setVisible(false);
        jLabel3.setVisible(true);
        magoDeGelo.setVisible(false);
        magoTrevoso.setVisible(false);
        GuerreiroEspadaFlamejante.setVisible(false);
        jLabel2.setVisible(true);
        guerreiroCruz.setVisible(false);

        //getMagoImage();
        //getGuerreiroImage();

        Random random = new Random();
        int vezJogador = random.nextInt(2) + 1;  // Gera 1 ou 2 aleatoriamente

        if (vezJogador == 1) {
            ataqueGuerreiroBtn.setVisible(true);
            ataqueMagoBtn.setVisible(false);
        } else if (vezJogador == 2) {
            ataqueGuerreiroBtn.setVisible(false);
            ataqueMagoBtn.setVisible(true);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        GuerreiroEspadaFlamejante = new javax.swing.JLabel();
        guerreiroCruz = new javax.swing.JLabel();
        magoDeGelo = new javax.swing.JLabel();
        magoTrevoso = new javax.swing.JLabel();
        labelDanoMago = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        labelVitoria = new javax.swing.JLabel();
        ataqueGuerreiroBtn = new javax.swing.JButton();
        labelDanoGuerreiro = new javax.swing.JLabel();
        ataqueMagoBtn = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        returnButton = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 960));
        setMinimumSize(new java.awt.Dimension(1280, 960));
        setResizable(false);
        getContentPane().setLayout(null);
        getContentPane().add(jLabel11);
        jLabel11.setBounds(870, 330, 130, 30);

        GuerreiroEspadaFlamejante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/GuerreiroEspada.png"))); // NOI18N
        getContentPane().add(GuerreiroEspadaFlamejante);
        GuerreiroEspadaFlamejante.setBounds(280, 340, 290, 340);

        guerreiroCruz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/GuerreiroCruzpng.png"))); // NOI18N
        getContentPane().add(guerreiroCruz);
        guerreiroCruz.setBounds(290, 350, 300, 300);

        magoDeGelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/MagoGelo.png"))); // NOI18N
        getContentPane().add(magoDeGelo);
        magoDeGelo.setBounds(750, 300, 290, 420);

        magoTrevoso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/MagoMal.png"))); // NOI18N
        getContentPane().add(magoTrevoso);
        magoTrevoso.setBounds(750, 300, 290, 420);

        labelDanoMago.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        labelDanoMago.setForeground(new java.awt.Color(255, 0, 0));
        labelDanoMago.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(labelDanoMago);
        labelDanoMago.setBounds(830, 290, 90, 50);

        jTextField3.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jTextField3.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField3.setEnabled(false);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(840, 720, 140, 30);

        jTextField5.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jTextField5.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField5.setEnabled(false);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(840, 760, 140, 30);
        getContentPane().add(labelVitoria);
        labelVitoria.setBounds(520, 240, 270, 100);

        ataqueGuerreiroBtn.setText("Ataque");
        ataqueGuerreiroBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ataqueGuerreiroBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ataqueGuerreiroBtn);
        ataqueGuerreiroBtn.setBounds(390, 660, 70, 40);

        labelDanoGuerreiro.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        labelDanoGuerreiro.setForeground(new java.awt.Color(255, 0, 0));
        labelDanoGuerreiro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(labelDanoGuerreiro);
        labelDanoGuerreiro.setBounds(460, 280, 90, 50);

        ataqueMagoBtn.setText("Ataque");
        ataqueMagoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ataqueMagoBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ataqueMagoBtn);
        ataqueMagoBtn.setBounds(880, 660, 70, 40);

        jTextField6.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jTextField6.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField6.setEnabled(false);
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6);
        jTextField6.setBounds(840, 800, 140, 30);

        jLabel9.setForeground(new java.awt.Color(250, 250, 250));
        jLabel9.setText("Defesa");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(1000, 810, 50, 16);

        jLabel7.setForeground(new java.awt.Color(250, 250, 250));
        jLabel7.setText("Ataque");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(1000, 770, 50, 16);

        jLabel10.setForeground(new java.awt.Color(250, 250, 250));
        jLabel10.setText("Vida");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(1000, 730, 50, 16);

        jTextField1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jTextField1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField1.setEnabled(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(360, 720, 140, 30);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(360, 330, 140, 30);

        jLabel4.setForeground(new java.awt.Color(250, 250, 250));
        jLabel4.setText("Vida");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(290, 730, 50, 16);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/MagoNormal.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(770, 300, 290, 420);

        jLabel6.setForeground(new java.awt.Color(250, 250, 250));
        jLabel6.setText("Ataque");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(290, 770, 50, 16);

        jTextField2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jTextField2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField2.setEnabled(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(360, 760, 140, 30);

        jLabel8.setForeground(new java.awt.Color(250, 250, 250));
        jLabel8.setText("Defesa");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(290, 810, 50, 16);

        returnButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/CCghb2jmusREZesANOmAbsgIBN7nI9VZPDfnxPHhHxjaDuuU5QkBzzBxN9mSHWkp8x2MNHo9eTnaK9dM1AhqBY2rV1RM3IQSO9s1ytEbEKT6sdOAwP8HblzPDyaVCfsAAAAASUVORK5CYII.png"))); // NOI18N
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });
        getContentPane().add(returnButton);
        returnButton.setBounds(590, 820, 160, 80);

        jTextField4.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jTextField4.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField4.setEnabled(false);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(360, 800, 140, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Guerreiro.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(270, 240, 300, 540);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/batalha-fundo.jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setToolTipText("");
        jLabel1.setMaximumSize(new java.awt.Dimension(1280, 960));
        jLabel1.setMinimumSize(new java.awt.Dimension(1280, 960));
        jLabel1.setPreferredSize(new java.awt.Dimension(1280, 960));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 0, 1270, 960);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
//GEN-FIRST:event_jTextField1ActionPerformed
        //TODO add your handling code here:

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed
    /*private void getGuerreiroImage() {
        CadastroPersonagem cp = new CadastroPersonagem();
        String tipoGuerreiro = cp.getGuerreiroImage();
        System.out.println(tipoGuerreiro);

        if (tipoGuerreiro == "Espada Flamejante") {

            jLabel2.setVisible(false);
            guerreiroCruz.setVisible(false);
            GuerreiroEspadaFlamejante.setVisible(true);
        }

        if (tipoGuerreiro == "<Vazio>") {

            jLabel2.setVisible(true);
            guerreiroCruz.setVisible(false);
            GuerreiroEspadaFlamejante.setVisible(false);

        }

        if (tipoGuerreiro == "Crucifixo") {

            GuerreiroEspadaFlamejante.setVisible(false);
            jLabel2.setVisible(false);
            guerreiroCruz.setVisible(true);

        }
    }

    private void getMagoImage() {

        CadastroPersonagem cp = new CadastroPersonagem();

        String tipoMago = cp.getMagoImage();
        if (tipoMago == "<Vazio>") {

            jLabel3.setVisible(false);
            magoTrevoso.setVisible(false);
            magoDeGelo.setVisible(true);
        }

        if (tipoMago == "Cajado De Gelo") {

            magoTrevoso.setVisible(false);
            jLabel3.setVisible(false);
            magoDeGelo.setVisible(true);

        }

        if (tipoMago == "Grimorio das Sombras") {

            jLabel3.setVisible(false);
            magoDeGelo.setVisible(false);
            magoTrevoso.setVisible(true);

        }
    }
*/
    int i = 0;
    Guerreiro guerreiro;
    Mago mago;
    private void ataqueGuerreiroBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ataqueGuerreiroBtnActionPerformed

        labelDanoGuerreiro.setVisible(false);

        labelDanoMago.setVisible(false);

        if (i == 0) {
            mago = imprimeMago();
            guerreiro = imprimeGuerreiros();
            i++;
            j++;
        }

        mago = ataqueGuerreiro(guerreiro, mago);


    }//GEN-LAST:event_ataqueGuerreiroBtnActionPerformed
    int j = 0;
    private void ataqueMagoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ataqueMagoBtnActionPerformed

        labelDanoGuerreiro.setVisible(false);

        labelDanoMago.setVisible(false);

        if (j == 0) {
            mago = imprimeMago();
            guerreiro = imprimeGuerreiros();
            j++;
            i++;
        }

        guerreiro = ataqueMago(guerreiro, mago);


    }//GEN-LAST:event_ataqueMagoBtnActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        // TODO add your handling code here:
        TelaAbertura tela = new TelaAbertura();
        this.dispose();
        tela.setVisible(true);

    }//GEN-LAST:event_returnButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        TelaBatalha tela = new TelaBatalha();
        tela.setVisible(true);

    }

    private Guerreiro getGuerreiroBD() {
        Guerreiro guerreiro = new Guerreiro();

        String sql = "SELECT * FROM `tb_guerreiro` ORDER BY id_guerreiro DESC LIMIT 1;";

        try {
            PreparedStatement preparacaoDaInstrucao = Conexao.getConexao().prepareStatement(sql);
            ResultSet resultado = preparacaoDaInstrucao.executeQuery();
            resultado.next();
            guerreiro.setNome(resultado.getString("nome"));
            guerreiro.setPontosVida(resultado.getInt("ponto_vida"));
            guerreiro.setPontosAtaque(resultado.getInt("ponto_ataque"));
            guerreiro.setPontosDefesa(resultado.getInt("ponto_defesa"));
            guerreiro.setForca(resultado.getInt("forca"));
            guerreiro.setVelocidade(resultado.getInt("velocidade"));
        } catch (SQLException ex) {
            Logger.getLogger(VerGuerreiro.class.getName()).log(Level.SEVERE, null, ex);
        }

        return guerreiro;
    }

    private Guerreiro imprimeGuerreiros() {

        Guerreiro guerreiro = new Guerreiro();

        String sql = "SELECT * FROM `tb_guerreiro` ORDER BY id_guerreiro DESC LIMIT 1;";
        String vida, nome, ataque, defesa;

        try {
            PreparedStatement preparacaoDaInstrucao = Conexao.getConexao().prepareStatement(sql);
            ResultSet resultado = preparacaoDaInstrucao.executeQuery();

            while (resultado.next()) {
                guerreiro.setNome(resultado.getString("nome"));
                guerreiro.setPontosVida(resultado.getInt("ponto_vida"));
                guerreiro.setPontosAtaque(resultado.getInt("ponto_ataque"));
                guerreiro.setPontosDefesa(resultado.getInt("ponto_defesa"));
//                guerreiro.setForca(resultado.getInt("forca"));
//                guerreiro.setVelocidade(resultado.getInt("velocidade"));
                vida = "" + guerreiro.getPontosVida();
                nome = "" + guerreiro.getNome();
                ataque = "" + guerreiro.getPontosAtaque();
                defesa = "" + guerreiro.getPontosDefesa();

                jTextField2.setText(ataque);
                jTextField4.setText(defesa);
                jLabel5.setText(nome);
                jTextField1.setText(vida);
            }
        } catch (SQLException ex) {
            Logger.getLogger(VerGuerreiro.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
        return guerreiro;
    }

    private Mago imprimeMago() {

        Mago mago = new Mago();

        String sql = "SELECT * FROM `tb_mago` ORDER BY id_mago DESC LIMIT 1;";
        String vida, nome, ataque, defesa;

        try {
            PreparedStatement preparacaoDaInstrucao = Conexao.getConexao().prepareStatement(sql);
            ResultSet resultado = preparacaoDaInstrucao.executeQuery();

            while (resultado.next()) {
                mago.setNome(resultado.getString("nome"));
                mago.setPontosVida(resultado.getInt("ponto_vida"));
                mago.setPontosAtaque(resultado.getInt("ponto_ataque"));
                mago.setPontosDefesa(resultado.getInt("ponto_defesa"));
//                guerreiro.setForca(resultado.getInt("forca"));
//                guerreiro.setVelocidade(resultado.getInt("velocidade"));
                vida = "" + mago.getPontosVida();
                nome = "" + mago.getNome();
                ataque = "" + mago.getPontosAtaque();
                defesa = "" + mago.getPontosDefesa();

                jTextField5.setText(ataque);
                jTextField6.setText(defesa);
                jLabel11.setText(nome);
                jTextField3.setText(vida);

            }
        } catch (SQLException ex) {
            Logger.getLogger(VerGuerreiro.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();

        }
        return mago;
    }

    private Mago ataqueGuerreiro(Guerreiro guerreiro, Mago mago) {
        double vidaMago = mago.getPontosVida();
        double defesaMago = mago.getPontosDefesa();
        double ataqueGuerreiro = guerreiro.getPontosAtaque();

        Random random = new Random();
        double multiplicadorDano = (random.nextInt(20) + 1) * 0.5;

        double dano = Math.max((ataqueGuerreiro - defesaMago) * multiplicadorDano, 0);
        vidaMago = Math.max(vidaMago - dano, 0);
        mago.setPontosVida(vidaMago);

        String stringVidaMago = "" + vidaMago;
        jTextField3.setText(stringVidaMago);

        labelDanoMago.setText("-" + dano);
        labelDanoMago.setVisible(true);

        if (vidaMago == 0) {
            ataqueMagoBtn.setVisible(false);
            ataqueGuerreiroBtn.setVisible(false);

            labelVitoria.setText(mago.getNome() + " Venceu!!");
            labelVitoria.setVisible(true);
            returnButton.setVisible(true);

            salvar(guerreiro);
        } else {
            ataqueMagoBtn.setVisible(true);
            ataqueGuerreiroBtn.setVisible(false);
            labelDanoGuerreiro.setVisible(false);

        }

        return mago;
    }

    private Guerreiro ataqueMago(Guerreiro guerreiro, Mago mago) {
        double ataqueMago = mago.getPontosAtaque();
        double vidaGuerreiro = guerreiro.getPontosVida();
        double defesaGuerreiro = guerreiro.getPontosDefesa();

        Random random = new Random();
        double multiplicadorDano = (random.nextInt(20) + 1) * 0.5;

        double dano = Math.max((ataqueMago - defesaGuerreiro) * multiplicadorDano, 0);
        vidaGuerreiro = Math.max(vidaGuerreiro - dano, 0);
        guerreiro.setPontosVida(vidaGuerreiro);

        String stringVidaGuerreiro = "" + vidaGuerreiro;
        jTextField1.setText(stringVidaGuerreiro);

        labelDanoGuerreiro.setText("-" + dano);
        labelDanoGuerreiro.setVisible(true);

        if (vidaGuerreiro == 0) {
            ataqueMagoBtn.setVisible(false);
            ataqueGuerreiroBtn.setVisible(false);

            labelVitoria.setText(mago.getNome() + " Venceu!!");
            labelVitoria.setVisible(true);
            labelDanoGuerreiro.setVisible(false);
            returnButton.setVisible(true);

            salvar(mago);
        } else {
            ataqueMagoBtn.setVisible(false);
            ataqueGuerreiroBtn.setVisible(true);

        }

        return guerreiro;
    }

    private void batalha(Mago mago, Guerreiro guerreiro, int vezJogador) { // Recebe 2 personagens um guerreiro e um mago
        // Pegando atributos dos personagens
        double vidaMago = mago.getPontosVida();
        double ataqueMago = mago.getPontosAtaque();
        double defesaMago = mago.getPontosDefesa();
        double vidaGuerreiro = guerreiro.getPontosVida();
        double ataqueGuerreiro = guerreiro.getPontosAtaque();
        double defesaGuerreiro = guerreiro.getPontosDefesa();

        Random random = new Random();
        // Use a classe Random para decidir aleatoriamente quem ataca primeiro
        double multiplicadorDano = (random.nextInt(20) + 1) * 0.5;

        labelDanoGuerreiro.setVisible(false);
        labelDanoMago.setVisible(false);
        if (vezJogador == 1) { // Vez do guerreiro

        } else if (vezJogador == 2) { // Vez do mago
            double dano = Math.max((ataqueMago - defesaGuerreiro) * multiplicadorDano, 0);
            vidaGuerreiro = Math.max(vidaGuerreiro - dano, 0);
            String stringVidaGuerreiro = "" + vidaGuerreiro;
            jTextField1.setText(stringVidaGuerreiro);
            vezJogador = 1;

            labelDanoGuerreiro.setText("-" + dano);
            labelDanoGuerreiro.setVisible(true);

            guerreiro.setPontosVida(vidaGuerreiro);

        }
    }

    private void salvar(Mago mago) {
        String sql = "INSERT INTO `tb_batalha`(`nome_vencedor`)"
                + "VALUES "
                + "(?);";
        try {
            PreparedStatement preparacaoDaInstrucao = Conexao.getConexao().prepareStatement(sql);
            preparacaoDaInstrucao.setString(1, mago.getNome());
            preparacaoDaInstrucao.executeUpdate();

            // libera a memória da janela
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void salvar(Guerreiro guerreiro) {
        String sql = "INSERT INTO `tb_batalha`(`nome_vencedor`)"
                + "VALUES "
                + "(?);";
        try {
            PreparedStatement preparacaoDaInstrucao = Conexao.getConexao().prepareStatement(sql);
            preparacaoDaInstrucao.setString(1, guerreiro.getNome());
            preparacaoDaInstrucao.executeUpdate();

            // libera a memória da janela
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GuerreiroEspadaFlamejante;
    private javax.swing.JButton ataqueGuerreiroBtn;
    private javax.swing.JButton ataqueMagoBtn;
    private javax.swing.JLabel guerreiroCruz;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel labelDanoGuerreiro;
    private javax.swing.JLabel labelDanoMago;
    private javax.swing.JLabel labelVitoria;
    private javax.swing.JLabel magoDeGelo;
    private javax.swing.JLabel magoTrevoso;
    private javax.swing.JButton returnButton;
    // End of variables declaration//GEN-END:variables
}
