/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.ifpr.thelaststanding;

import br.edu.ifpr.thelaststanding.conexao.Conexao;
import br.edu.ifpr.thelaststanding.personagens.Guerreiro;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Aluno
 */
public class TelaBatalha extends javax.swing.JFrame {

    /**
     * Creates new form TelaBatalha
     */
    public TelaBatalha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 960));
        setMinimumSize(new java.awt.Dimension(1280, 960));
        setResizable(false);
        getContentPane().setLayout(null);

        jTextField1.setEnabled(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(360, 720, 140, 30);

        jLabel4.setForeground(new java.awt.Color(250, 250, 250));
        jLabel4.setText("Vida");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(290, 730, 50, 16);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/MagoNormal.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(770, 300, 290, 420);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Guerreiro.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(270, 240, 300, 540);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/batalha-fundo.jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(1280, 960));
        jLabel1.setMinimumSize(new java.awt.Dimension(1280, 960));
        jLabel1.setPreferredSize(new java.awt.Dimension(1280, 960));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1280, 960);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
        //GEN-FIRST:event_jTextField1ActionPerformed
        //TODO add your handling code here:

    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaBatalha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaBatalha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaBatalha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaBatalha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
         /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaBatalha().setVisible(true);
            }
        });
    }
    private Guerreiro getGuerreiro(){
        Guerreiro guerreiro = new Guerreiro();

        String sql = "SELECT * FROM `tb_guerreiro` ORDER BY id_guerreiro DESC LIMIT 1;";

        try {
            PreparedStatement preparacaoDaInstrucao = Conexao.getConexao().prepareStatement(sql);
            ResultSet resultado = preparacaoDaInstrucao.executeQuery();
            resultado.next();
            guerreiro.setNome(resultado.getString("nome"));
            guerreiro.setPontosVida(resultado.getInt("ponto_vida"));
            guerreiro.setPontosAtaque(resultado.getInt("ponto_ataque"));
            guerreiro.setPontosDefesa(resultado.getInt("ponto_defesa"));
            guerreiro.setForca(resultado.getInt("forca"));
            guerreiro.setVelocidade(resultado.getInt("velocidade"));
        } catch (SQLException ex) {
            Logger.getLogger(VerGuerreiro.class.getName()).log(Level.SEVERE, null, ex);
        }

        return guerreiro;
    }
    private void imprimeGuerreiros() {

        Guerreiro guerreiro = new Guerreiro();

        String sql = "SELECT * FROM `tb_guerreiro` ORDER BY id_guerreiro DESC LIMIT 1;";

        try {
            PreparedStatement preparacaoDaInstrucao = Conexao.getConexao().prepareStatement(sql);
            ResultSet resultado = preparacaoDaInstrucao.executeQuery();

            while (resultado.next()) {
                guerreiro.setNome(resultado.getString("nome"));
                guerreiro.setPontosVida(resultado.getInt("ponto_vida"));
                guerreiro.setPontosAtaque(resultado.getInt("ponto_ataque"));
                guerreiro.setPontosDefesa(resultado.getInt("ponto_defesa"));
                guerreiro.setForca(resultado.getInt("forca"));
                guerreiro.setVelocidade(resultado.getInt("velocidade"));
                System.out.println(guerreiro.toString());
            }
        } catch (SQLException ex) {
            Logger.getLogger(VerGuerreiro.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
